name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run packer.bat script
        run: |
          script\packer.bat

      - name: Compress build artifacts
        run: |
          Compress-Archive -Path dist\MapleLabel\* -DestinationPath MapleLabel.zip
        shell: pwsh

      - name: Set up GitHub CLI
        run: |
          choco install gh
        shell: pwsh

      - name: Check if release exists
        id: check_release
        run: |
          $tag_name = $env:GITHUB_REF -replace 'refs/tags/', ''
          $release = gh release view $tag_name --json url 2>$null
          if ($null -eq $release) {
            echo "::set-output name=release_exists::false"
          } else {
            echo "::set-output name=release_exists::true"
          }
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}

      - name: Create or Update Release
        run: |
          $tag_name = $env:GITHUB_REF -replace 'refs/tags/', ''
          if (${{ steps.check_release.outputs.release_exists }} -eq 'false') {
            gh release create $tag_name ./MapleLabel.zip -t $tag_name -n "Release for $tag_name"
          } else {
            gh release upload $tag_name ./MapleLabel.zip --clobber
          }
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
