name: Build Executable and Release
on: 
  push:
    tags:
      - '*'  # 任何tag都会触发工作流
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Run build script
      run: .\script\packer.bat
      shell: cmd

    - name: Zip files
      run: Compress-Archive -Path dist\MapleLabel\* -DestinationPath MapleLabel.zip
      shell: powershell

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: MapleLabel
        path: MapleLabel.zip
