name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run packer.bat script
        run: |
          script\packer.bat

      - name: Compress build artifacts
        run: |
          Compress-Archive -Path dist\MapleLabel\* -DestinationPath MapleLabel.zip
        shell: pwsh

      - name: Check if release exists
        id: check_release
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          if gh release view "$TAG_NAME"; then
            echo "::set-output name=release_exists::true"
          else
            echo "::set-output name=release_exists::false"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create or Update Release
        id: create_or_update_release
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          if [ "${{ steps.check_release.outputs.release_exists }}" == "false" ]; then
            gh release create "$TAG_NAME" "./MapleLabel.zip" -t "$TAG_NAME" -n "Release for $TAG_NAME"
          else
            gh release upload "$TAG_NAME" "./MapleLabel.zip" --clobber
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
